### ISSUE TITLE
(krypton) Command doesn't work in console

### ISSUE THREAD

**Issue by Sliman4** [MiniPlaceholders/MiniPlaceholders#11]
Because of this:
https://github.com/MiniPlaceholders/MiniPlaceholders/blob/5e8a881b517fea385598ad4d08d7b6df7b4dbc58/common/src/main/java/me/dreamerzero/miniplaceholders/common/PlaceholdersCommand.java#L50

**Comment by 4drian3d** [comment]
Apparently, Krypton does not implement the Adventure Pointers that are necessary for the command to work correctly https://github.com/KryptonMC/Krypton/issues/82

**Comment by 4drian3d** [comment]
Fixed in Krypton https://github.com/KryptonMC/Krypton/commit/5e70bac3ecbc2d4d0a8144809371e0d0b91de503
