### ISSUE TITLE
`/miniplaceholders` doesn't display placeholder count

### ISSUE THREAD

**Issue by Sliman4** [MiniPlaceholders/MiniPlaceholders#12]
It should display placeholder count for players with permission, and plugin version for players without permission. But `PermissionChecker` requires `TriState.TRUE`, and players may have a permission enabled by default. Server operators have all `default: op` permissions implicitly with `NOT_SET`, maybe there are other such cases. So even if I `/op` myself, I still get MiniPlaceholders' version in `/miniplaceholders`

**Comment by 4drian3d** [comment]
This problem seems to be specific to Paper that does not return the proper Tristate. Still, it would be ideal to use a permissions plugin like LuckPerms to manage server permissions instead of a buggy system like Minecraft vanilla's "op"
