### ISSUE TITLE
/miniplaceholders parse can be executed without permission

### ISSUE THREAD

**Issue by Sliman4** [MiniPlaceholders/MiniPlaceholders#13]
Permission check only exists in `/miniplaceholders` with no arguments, `/miniplaceholders parse` and `/miniplaceholders help` both can be used by all players.

**Comment by 4drian3d** [comment]
On which platform are you testing it? If it is on Krypton, it currently has a problem with the Pointers system

**Comment by 4drian3d** [comment]
Ok, I saw the problem, although I'm sure I fixed it a long time ago... Maybe it was in another branch and I didn't notice it

**Comment by 4drian3d** [comment]
In effect, it was in another branch https://github.com/MiniPlaceholders/MiniPlaceholders/commit/39c7455b5385c2d49dacb461b633745f7fadc550 apologies for this bug, now I release a new release fixing it
