### ISSUE TITLE
Relational placeholders don't work (am I doing it wrong?)

### ISSUE THREAD

**Issue by marlester-dev** [MiniPlaceholders/MiniPlaceholders#170]
so I've got an expansion of my plugin: 
```
Expansion.builder("internal")
        .filter(Player.class)
        .audiencePlaceholder("player_name", (audience, queue, ctx) -> {
          return getPlayerNameTag(audience);
        })
        .filter(Player.class)
        .relationalPlaceholder("1_player_name", (audience, otherAudience, queue, ctx) -> {
          return getPlayerNameTag(audience);
        })
        .filter(Player.class)
        .relationalPlaceholder("2_player_name", (audience, otherAudience, queue, ctx) -> {
          return getPlayerNameTag(otherAudience);
        })
        .build();
```
But neither "internal_1_player_name" nor "internal_2_player_name" work, I just use the expansion.relationalPlaceholders(player, anotherPlayer)
I also tried with "rel_" prefix but didn't work either
internal_player_name when used with expansion.audiencePlaceholders(player) works though

**Comment by 4drian3d** [comment]
What is the result of `getPlayerNameTag(audience)`?
Also, you don't need to reassign the class filter every time, it is only required once and it doesn't matter the order in which it is done

**Comment by 4drian3d** [comment]
Sorry, it seems that the documentation doesn't specify how relational placeholders work, but that's more or less how it would be:

![image](https://github.com/MiniPlaceholders/MiniPlaceholders/assets/68704415/799814ac-8843-4327-ae22-f308037a488d)

`<some_expansion_rel_placeholder>` -> `<[expansion name]_rel_[placeholder name]>`

_I will now improve the relational placeholders section_
