### ISSUE TITLE
paper brigadier initialization failure on 2.2.4 & 2.3 snapshots 

### ISSUE THREAD

**Issue by n-aspen** [MiniPlaceholders/MiniPlaceholders#208]
The latest [2.2.4](https://modrinth.com/plugin/miniplaceholders/version/J2guR3GH) release on Modrinth and the most recent build action as of writing for 2.3.0 both get the following error on Paper 1.21

https://mclo.gs/ubkQDAy

**Comment by 4drian3d** [comment]
https://github.com/MiniPlaceholders/MiniPlaceholders/pull/199#pullrequestreview-2186775985

**Comment by 4drian3d** [comment]
Try latest build

**Comment by 4drian3d** [comment]
Fixed in #199
